# Dockerfile.airflow
FROM apache/airflow:2.7.3-python3.9

USER root

# installer libgomp1 pour LightGBM
RUN apt-get update \
 && apt-get install -y --no-install-recommends libgomp1 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

#  RUN pip install evidently==0.7.8

USER airflow

# (Optionnel) vous pouvez aussi copier et installer vos requirements ici
# COPY requirements.txt /requirements.txt
# RUN pip install --no-cache-dir -r /requirements.txt
